version: "3.7"

services:
  app:
    image: eqtest
    ports:
      - 8080:8080
  environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_DB: "mtv_ctc"

mysql:
  image: "mysql:8.0.13"
  volumes:
    - ./test-mysql-data:/var/lib/mysql
  environment:
      MYSQL_ROOT_PASSWORD: "" 
      MYSQL_DATABASE: "mtv_ctc"